server:
    port: 8088
spring:
    application:
        name: category-product-composite-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        instance:
            preferIpAddress: true
            leaseRenewalIntervalInSeconds: 5
            metadataMap:
                instanceId: '${spring.application.name}:${random.value}'
hystrix:
    dashboard:
        proxy-stream-allow-list: '*'
management:
    endpoints:
        web:
            exposure:
                include: '*'
security:
    oauth2:
        resource:
            jwk:
                key-set-uri: http://auth:8088/oauth2/keys
