spring:
    application:
        name: category-product-composite-service
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        instance:
            preferIpAddress: true
            leaseRenewalIntervalInSeconds: 5
            metadataMap:
                instanceId: '${spring.application.name}:${random.value}'
