server:
    port: 8081
eureka:
    client:
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
    instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
zuul:
    ignoredServices: '*'
    routes:
        users:
            path: /user/**
            serviceId: user-role-service
        products:
            path: /products/**
            serviceId: category-product-composite-service
        categories:
            path: /categories/**
            serviceId: category-product-composite-service
