server:
    port: 8081
eureka:
    client:
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        healthCheck:
            enabled: true
    instance:
        prefer-ip-address: true
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /info
        healthCheckUrlPath: /health
zuul:
    ignoredServices: '*'
    routes:
        users:
            path: /user/**
            serviceId: user-role-service
        category_product:
            path: /cmp/**
            serviceId: category-product-composite-service
management:
    endpoints:
        web:
            exposure:
                include: '*'
hystrix:
    dashboard:
        proxy-stream-allow-list: '*'
