server:
    port: 8088
spring:
    application:
        name: auth

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        instance:
            preferIpAddress: true
            leaseRenewalIntervalInSeconds: 5
            metadataMap:
                instanceId: '${spring.application.name}:${random.value}'
security:
    oauth2:
        client:
            client-id: webshop-client
            client-secret: strong
            auth-server-client-credentials:
                access-token-uri: http://user-role-service:8080/oauth/token
                client-id: auth-client
                client-secret: secret
                grant-type: client_credentials
                scope: read

logging:
    level:
        org:
            springframework:
                web: DEBUG
