server:
    port: 8088
spring:
    application:
        name: auth

eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        instance:
            preferIpAddress: true
            leaseRenewalIntervalInSeconds: 5
            metadataMap:
                instanceId: '${spring.application.name}:${random.value}'
security:
    oauth2:
        client:
            client-id: webshop-client
            client-secret: strong

logging:
    level:
        org:
            springframework:
                web: DEBUG
