server:
    port: 8088
spring:
    application:
        name: auth
    datasource:
        url: jdbc:mysql://mysql_categories:3306/webshop
        password: shop
        username: shop
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create-drop
eureka:
    client:
        serviceUrl:
            defaultZone: http://eureka-server:8761/eureka/
        instance:
            preferIpAddress: true
            leaseRenewalIntervalInSeconds: 5
            metadataMap:
                instanceId: '${spring.application.name}:${random.value}'
